#!/bin/env sh

# repository
REPO="SpotifyControl"
USER="chiayolin"
HOST="github.com"

# symlink
PATH="/usr/local/bin"
NAME="spotify"

# clone it, and cd inside
git clone https://$HOST/$USER/$REPO \ 
  && cd $REPO

# make a symlink
ln -is $(pwd)/$REPO $PATH/$NAME
