#!/bin/env sh
# This script makes symlink to `/usr/local/bin/` only.
# To install elsewhere, just modify the value of SPATH,
# or use any other method you like.
SREPO="SpotifyControl"
SUSER="chiayolin"
SHOST="github.com"
SPATH="/usr/local/bin"
SNAME="spotify"

git clone https://$SHOST/$SUSER/$SREPO \
  && cd $SREPO && ln -is $(pwd)/$SREPO $SPATH/$SNAME
